import {
  Img1,
  Img2,
  Img3,
  Img4,
  Img5,
  Profile1,
  Profile2,
  Profile3,
  Profile4,
  Profile5,
  Profile6,
  Profile7,
  Profile8,
  Profile9,
} from "../assets/images/icons/icons";

export const dummyData = [
  {
    id: 1,
    profile: Profile1,
    title: "Nicholas White",
    verified: true,
    follow: true,
    niche: "Engineer, Content Creator, & Educator",
    time: "1w",
    content:
      " Breaking into data science in 2024? Here&apos;s what actually matters: 📊 SQL (you&apos;ll use this daily) 🐍 Python fundamentals📈 Statistics & probability 🧠 Domain knowledge 💬 Communication skills The fancy ML algorithms? You&apos;ll learn those on the job.Focus on the foundations first.",
    tags: "#programmer #coding #softwareengineer #work",
    image: Img1,
    emoji: ["like", "love", "clap"],
    likes: 42,
    comments: 8,
    reposts: 6,
  },
  {
    id: 2,
    profile: Profile2,
    title: "Sarah Johnson",
    verified: false,
    follow: true,
    niche: "Android Developer @Redcliffe Labs",
    time: "3d",
    content:
      "Networking tips for developers: Always be curious and ask questions!",
    tags: "#programmer #coding #softwareengineer #work",
    image: Img4,
    emoji: ["like", "love"],
    likes: 67,
    comments: 15,
    reposts: 61,
  },
  {
    id: 3,
    profile: Profile3,
    title: "Mike Chen",
    verified: true,
    follow: false,
    niche: "|Kotlin | java | DSA Problem 550+",
    time: "1w",
    tags: "#programmer #coding #softwareengineer #work",
    image: Img2,
    emoji: ["like"],
    content:
      "Just landed a new job at TechCorp. Grateful for the opportunities!",
    likes: 89,
    comments: 22,
    reposts: 1,
  },
  {
    id: 4,
    profile: Profile4,
    title: "Emma Davis",
    niche:
      "Manager Learning & Development | People Centric | Life Coach | Senior Analyst",
    verified: true,
    follow: true,
    time: "1d",
    tags: "#programmer #coding #softwareengineer #work",
    image: Img3,
    emoji: ["like"],
    content:
      "React Native development is so much fun. Who's building mobile apps?",
    likes: 34,
    comments: 12,
    reposts: 10,
  },
  {
    id: 5,
    profile: Profile1,
    title: "Alex Rodriguez",
    verified: false,
    follow: true,
    niche: "Full Stack Developer & Tech Writer",
    time: "2d",
    content:
      "TypeScript is a game changer for large-scale projects. Worth the learning curve!",
    tags: "#typescript #webdev #programming #javascript",
    emoji: ["like", "love"],
    likes: 56,
    comments: 19,
    reposts: 23,
  },
  {
    id: 6,
    profile: Profile5,
    title: "Jessica Lee",
    verified: true,
    follow: false,
    niche: "Data Science and Business Analytics Intern at The Spark Foundation",
    time: "4d",
    content:
      "Just published my article on machine learning best practices. Check it out!",
    tags: "#machinelearning #AI #datascience #deeplearning",
    emoji: ["like", "clap"],
    likes: 123,
    comments: 34,
    reposts: 45,
  },
  {
    id: 7,
    profile: Profile6,
    title: "David Park",
    verified: true,
    follow: true,
    niche: "Cloud Architect & DevOps Expert",
    time: "5h",
    content:
      "Cloud infrastructure is evolving fast. Which platforms are you using in 2026?",
    tags: "#cloud #devops #aws #architecture",
    image: Img4,
    emoji: ["like", "love"],
    likes: 78,
    comments: 26,
    reposts: 12,
  },
  {
    id: 8,
    profile: Profile7,
    title: "Sofia Martinez",
    verified: false,
    follow: true,
    niche: "Product Manager & Tech Enthusiast",
    time: "1d",
    content:
      "Building a product that solves real problems is more important than chasing hype.",
    tags: "#productmanagement #tech #startup #innovation",
    emoji: ["like", "clap"],
    likes: 92,
    comments: 31,
    reposts: 18,
  },
  {
    id: 9,
    profile: Profile8,
    title: "James Wilson",
    verified: true,
    follow: true,
    niche: "Senior Software Engineer",
    time: "3h",
    content:
      "Code reviews are not about criticism, they&apos;re about learning together as a team.",
    tags: "#teamwork #coding #bestpractices #softwaredevelopment",
    emoji: ["like", "love", "clap"],
    likes: 145,
    comments: 42,
    reposts: 67,
  },
  {
    id: 10,
    profile: Profile9,
    title: "GitHub",
    verified: true,
    follow: true,
    niche: "Software Architecture & Cloud Services",
    time: "6h",
    content: "Design systems are the backbone of scalable digital products.",
    tags: "#design #ux #frontend #figma",
    image: Img5,
    emoji: ["like"],
    likes: 64,
    comments: 17,
    reposts: 9,
  },
];
